[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = 'python'
hook_add = '''
  let g:syntastic_python_checkers = ['pyflakes', 'pep8']
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'
